# Generated by Django 4.1.7 on 2023-03-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='status',
            field=models.CharField(choices=[('A', 'Активный'), ('I', 'Неактивный'), ('F', 'Замороженный')], max_length=1),
        ),
    ]
